### ISSUE TITLE
Clean task must be run when switching build architectures or updating JNI dependency versions

### ISSUE THREAD

**Issue by mcm001** [wpilibsuite/wpilib-tool-plugin#17]
Steps to reproduce (at least, in Photon -- working to confirm in Shuffleboard)

```
./gradlew clean
./gradlew build
./gradlew build -PArchOverride=linuxarm32
```
After this, observe that the native artifacts in the shaded JAR spat out are not in fact arm32 -- they should be the host architecture instead. I can also get unsatisfied link exceptions when bumping JNI dependency versions which include JNI changes without first running clean -- and after running clean and rebuilding, the unsatisfied link exceptions are gone.

**Comment by mcm001** [comment]
Just confirmed these steps work with Photon at least:

`./gradlew clean`
`./gradlew shadowjar -PArchOverride=linuxarm64`
Confirm the JAR spat out contains a `linux/arm64/shared` folder
`./gradlew shadowjar`
Confirm the JAR spat out does not contain a `linux/x86-64/shared` folder

**Comment by ThadHouse** [comment]
Figured this out. Its due to the extract configuration stuff using just the configuration name, rather then the actual extracted files. I'll fix it hopefully in the next week. Its not a trivial minimal line fix.

**Comment by mcm001** [comment]
Just reran, and it seems like the old artifacts aren't getting deleted, but the new ones _are_ being pulled in now? If I run a build on first linuxx86-64, then override to linuxarm64, I get a JAR with _both_ shared libs present.

**Comment by PeterJohnson** [comment]
That would make sense.. old stuff lives until you do a clean, and we generally use wildcards in zip tasks.
